name: cpplint CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cpplint
      run: pip install cpplint
    - name: Check files
      run: |
          cpplint src/main.c
          cpplint src/debug.h
